export const metadata = {
  title: "Create K8 Next App",
  description: "Generated by k8-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
